name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust-ci:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -Wclippy::pedantic -Dwarnings
      - name: testing
        run: cargo test --all
      - name: rustfmt
        run: cargo fmt --all -- --check
